// CheatCode OS — Mock Data
// All data is illustrative for UI/design purposes.
// Replace with real API calls when building out the backend.

export const marketSentiment = {
  label: "Bullish",
  description: "S&P 500 holding above 50-day MA. Breadth improving. Rotation into growth.",
  type: "bullish" as const,
  date: "Monday, April 7, 2025",
};

export const todaysPicks = [
  {
    id: "v1",
    type: "video" as const,
    youtubeId: "sBqD3YWLPWQ",
    title: "Minervini's VCP Setup: Why AMD and NFLX Are On My Radar Right Now",
    creatorId: "mark-minervini",
    creator: { name: "Mark Minervini", avatar: "MM", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/mark-minervini_a9c87f3e.jpg", color: "#12B76A" },
    thumbnail: "https://img.youtube.com/vi/sBqD3YWLPWQ/maxresdefault.jpg",
    duration: "18:42",
    quickTake: "Minervini breaks down VCP patterns. Relevant this week with XLK cooling and stock-picking outperforming sector bets. AMD and NFLX both on Kai's radar with convergence scores above 75.",
    tags: ["Technical Analysis", "Swing Trading"],
    relevanceBadge: "High Relevance",
    tickers: ["AMD", "NFLX"],
    convergenceScore: 78,
    publishedAt: "2h ago",
  },
  {
    id: "v2",
    type: "video" as const,
    youtubeId: "NpGSbSGJVNk",
    title: "The Private Credit Stress Signal Nobody Is Talking About",
    creatorId: "real-vision",
    creator: { name: "Real Vision", avatar: "RV", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/real-vision_f1b9eb10.jpg", color: "#2E90FA" },
    thumbnail: "https://img.youtube.com/vi/NpGSbSGJVNk/maxresdefault.jpg",
    duration: "34:15",
    quickTake: "Deep dive into private credit stress indicators. KKR and Ares Capital showing diverging signals. Part of Kai's 'Private-Credit-Stress' theme, escalating for 3 weeks.",
    tags: ["Macro", "Credit Markets"],
    relevanceBadge: "Critical",
    tickers: ["KKR", "ARCC", "BX"],
    convergenceScore: 91,
    publishedAt: "4h ago",
  },
  {
    id: "v3",
    type: "video" as const,
    youtubeId: "5RXUqzFYDkE",
    title: "Options Flow Alert: Unusual Activity in Semis — What Smart Money Is Doing",
    creatorId: "tastytrade",
    creator: { name: "tastytrade", avatar: "TT", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/tastytrade_cd3ffcd4.jpg", color: "#F79009" },
    thumbnail: "https://img.youtube.com/vi/5RXUqzFYDkE/maxresdefault.jpg",
    duration: "22:08",
    quickTake: "Unusual call buying in NVDA and SMCI ahead of earnings. Dark pool prints confirming institutional accumulation. Kai's Flow agent flagged this 6 hours before the video.",
    tags: ["Options", "Flow Analysis"],
    relevanceBadge: "High Relevance",
    tickers: ["NVDA", "SMCI", "AMD"],
    convergenceScore: 85,
    publishedAt: "6h ago",
  },
  {
    id: "v4",
    type: "video" as const,
    youtubeId: "dQw4w9WgXcQ",
    title: "Humbled Trader: My Exact Day Trading Setup for Volatile Markets",
    creatorId: "humbled-trader",
    creator: { name: "Humbled Trader", avatar: "HT", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/humbled-trader_13e6a711.jpg", color: "#F04438" },
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    duration: "28:33",
    quickTake: "Practical day trading framework for high-volatility environments. Specific setups for TSLA and SPY. Beginner-friendly but packed with actionable levels.",
    tags: ["Day Trading", "Psychology"],
    relevanceBadge: "Watch",
    tickers: ["TSLA", "SPY"],
    convergenceScore: 62,
    publishedAt: "8h ago",
  },
  {
    id: "v5",
    type: "video" as const,
    youtubeId: "nFZP8zQ3eKo",
    title: "Nuclear Renaissance: The Energy Trade of the Decade — Deep Dive",
    creatorId: "macro-voices",
    creator: { name: "Macro Voices", avatar: "MV", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/macro-voices_f2acb776.jpg", color: "#0EA5E9" },
    thumbnail: "https://img.youtube.com/vi/nFZP8zQ3eKo/maxresdefault.jpg",
    duration: "52:17",
    quickTake: "Comprehensive breakdown of the nuclear energy thesis. CCJ, NNE, and SMR all mentioned with specific price targets. Kai's 'Nuclear Renaissance' theme at escalation level 4.",
    tags: ["Macro", "Energy", "Sectors"],
    relevanceBadge: "Critical",
    tickers: ["CCJ", "NNE", "SMR", "CEG"],
    convergenceScore: 93,
    publishedAt: "Yesterday",
  },
  {
    id: "p1",
    type: "podcast" as const,
    youtubeId: "3NsQHBQDMaE",
    title: "All-In E172: Tariff Shock, Rate Cuts, and the AI Infrastructure Supercycle",
    creatorId: "all-in",
    creator: { name: "All-In Podcast", avatar: "AI", avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/all-in_421d15f4.jpg", color: "#2B3245" },
    thumbnail: "https://img.youtube.com/vi/3NsQHBQDMaE/maxresdefault.jpg",
    duration: "1:24:00",
    quickTake: "Chamath, Sacks, Friedberg, and Levchin debate tariff impacts on tech supply chains. Consensus: AI infrastructure spending is immune. MSFT, GOOGL, META all mentioned as beneficiaries.",
    tags: ["Macro", "Tech", "AI"],
    relevanceBadge: "High Relevance",
    tickers: ["MSFT", "GOOGL", "META", "AMZN"],
    convergenceScore: 80,
    publishedAt: "Yesterday",
  },
];

export const topicGrid = [
  { id: "technical-analysis", label: "Technical Analysis", icon: "📈", count: 284, color: "#ECFDF3" },
  { id: "options", label: "Options", icon: "⚡", count: 156, color: "#EFF8FF" },
  { id: "swing-trading", label: "Swing Trading", icon: "🎯", count: 198, color: "#FFFAEB" },
  { id: "day-trading", label: "Day Trading", icon: "⏱️", count: 143, color: "#FEF3F2" },
  { id: "macro", label: "Macro", icon: "🌍", count: 211, color: "#F5F3FF" },
  { id: "sectors", label: "Sectors", icon: "🏭", count: 167, color: "#FFF7ED" },
  { id: "crypto", label: "Crypto", icon: "₿", count: 89, color: "#ECFDF3" },
  { id: "fundamentals", label: "Fundamentals", icon: "📊", count: 134, color: "#EFF8FF" },
  { id: "psychology", label: "Psychology", icon: "🧠", count: 76, color: "#FFFAEB" },
];

export const hotThemes = [
  { id: "nuclear-renaissance", label: "Nuclear Renaissance", status: "Escalating", level: 4, tickers: ["CCJ", "NNE", "SMR"], score: 93, color: "#F79009" },
  { id: "private-credit-stress", label: "Private Credit Stress", status: "Escalating", level: 3, tickers: ["KKR", "ARCC", "BX"], score: 88, color: "#F04438" },
  { id: "ai-infrastructure", label: "AI Infrastructure Supercycle", status: "Active", level: 5, tickers: ["NVDA", "MSFT", "GOOGL"], score: 95, color: "#12B76A" },
  { id: "rate-cut-rotation", label: "Rate Cut Rotation", status: "Watch", level: 2, tickers: ["IWM", "XLF", "TLT"], score: 67, color: "#2E90FA" },
  { id: "china-tariff-impact", label: "China Tariff Impact", status: "New", level: 1, tickers: ["AAPL", "TSLA", "NKE"], score: 71, color: "#F79009" },
];

export const radarTickers = [
  { ticker: "NVDA", score: 95, direction: "Bullish", timeframe: "Swing", confidence: "Critical", change: "+2.4%" },
  { ticker: "CCJ", score: 93, direction: "Bullish", timeframe: "Position", confidence: "Critical", change: "+1.8%" },
  { ticker: "KKR", score: 88, direction: "Bearish", timeframe: "Swing", confidence: "High", change: "-1.2%" },
  { ticker: "AMD", score: 78, direction: "Bullish", timeframe: "Swing", confidence: "High", change: "+0.9%" },
  { ticker: "NFLX", score: 75, direction: "Bullish", timeframe: "Swing", confidence: "High", change: "+1.1%" },
  { ticker: "TSLA", score: 62, direction: "Bearish", timeframe: "Day", confidence: "Watch", change: "-2.1%" },
];

export const creators = [
  {
    id: "minervini",
    name: "Mark Minervini",
    handle: "@TheRealMarkMinervini",
    specialty: "VCP Patterns, Swing Trading",
    videoCount: 47,
    avatar: "MM",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/minervini_79e6c772.jpg",
    color: "#12B76A",
    verified: true,
    bio: "2-time U.S. Investing Champion and author of 'Trade Like a Stock Market Wizard'. Mark is famous for the VCP (Volatility Contraction Pattern) setup and has achieved returns of over 33,500% in a 5-year period.",
    tags: ["VCP", "Swing Trading", "Technical Analysis", "Growth Stocks"],
    youtubeUrl: "https://www.youtube.com/@TheRealMarkMinervini",
    topTickers: ["AMD", "NFLX", "NVDA", "SMCI"],
    kaiTake: "Minervini's VCP calls have a 78% convergence rate with Kai's technical agent. His setups tend to precede breakouts by 3-7 days on average.",
  },
  {
    id: "real-vision",
    name: "Real Vision",
    handle: "@realvision",
    specialty: "Macro, Institutional Research",
    videoCount: 89,
    avatar: "RV",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/real-vision_f1b9eb10.jpg",
    color: "#2E90FA",
    verified: true,
    bio: "Real Vision is the world's only video-on-demand channel for finance. Founded by Raoul Pal and Grant Williams, it brings together the world's best investors, economists, and traders to share their views.",
    tags: ["Macro", "Institutional", "Global Markets", "Deep Dives"],
    youtubeUrl: "https://www.youtube.com/@realvision",
    topTickers: ["KKR", "ARCC", "BX", "TLT"],
    kaiTake: "Real Vision's macro deep dives are the highest-signal content for Kai's regime classification agent. Their private credit coverage has been 2-3 weeks ahead of mainstream.",
  },
  {
    id: "tastytrade",
    name: "tastytrade",
    handle: "@tastytrade",
    specialty: "Options, Derivatives, Flow Analysis",
    videoCount: 134,
    avatar: "TT",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/tastytrade_cd3ffcd4.jpg",
    color: "#F79009",
    verified: true,
    bio: "tastytrade is a financial network for options and futures traders. Their research-driven approach to options trading has educated millions of retail traders on probability-based strategies and risk management.",
    tags: ["Options", "Derivatives", "Flow Analysis", "Probability"],
    youtubeUrl: "https://www.youtube.com/@tastytrade",
    topTickers: ["NVDA", "SMCI", "AMD", "SPY"],
    kaiTake: "tastytrade's options flow alerts have a strong correlation with Kai's unusual activity agent. Their NVDA and SMCI calls have been particularly accurate in the last 90 days.",
  },
  {
    id: "humbled-trader",
    name: "Humbled Trader",
    handle: "@HumbledTrader",
    specialty: "Day Trading, Psychology, Risk Management",
    videoCount: 62,
    avatar: "HT",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/humbled-trader_13e6a711.jpg",
    color: "#F04438",
    verified: true,
    bio: "Humbled Trader is a full-time day trader and educator known for her transparent, psychology-first approach to trading. She focuses on NASDAQ small caps and is known for her honest coverage of both wins and losses.",
    tags: ["Day Trading", "Psychology", "Small Cap", "NASDAQ"],
    youtubeUrl: "https://www.youtube.com/@HumbledTrader",
    topTickers: ["TSLA", "SPY", "QQQ", "NVDA"],
    kaiTake: "Humbled Trader's psychology content scores highest with Kai's sentiment agent. Her risk management frameworks align closely with Kai's position sizing recommendations.",
  },
  {
    id: "smb-capital",
    name: "SMB Capital",
    handle: "@smbcapital",
    specialty: "Prop Trading, Setups, Training",
    videoCount: 78,
    avatar: "SC",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/smb-capital_2e1bd09f.jpg",
    color: "#7C3AED",
    verified: true,
    bio: "SMB Capital is a proprietary trading firm and trading education company based in NYC. Founded by Mike Bellafiore and Steve Spencer, they train professional traders and share their methodologies publicly.",
    tags: ["Prop Trading", "Setups", "Professional", "NYC"],
    youtubeUrl: "https://www.youtube.com/@smbcapital",
    topTickers: ["NVDA", "AMD", "TSLA", "META"],
    kaiTake: "SMB Capital's playbook content has the highest institutional-grade signal density. Their sector rotation calls have preceded Kai's theme escalations by an average of 5 days.",
  },
  {
    id: "macro-voices",
    name: "Macro Voices",
    handle: "@MacroVoices",
    specialty: "Macro, Commodities, Global Themes",
    videoCount: 56,
    avatar: "MV",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/macro-voices_f2acb776.jpg",
    color: "#0EA5E9",
    verified: true,
    bio: "Macro Voices is a weekly podcast and video series hosted by Erik Townsend, featuring interviews with the world's top macro investors and economists. Known for deep commodity and energy analysis.",
    tags: ["Macro", "Commodities", "Energy", "Podcast"],
    youtubeUrl: "https://www.youtube.com/@MacroVoices",
    topTickers: ["CCJ", "NNE", "SMR", "CEG", "GLD"],
    kaiTake: "Macro Voices is the primary signal source for Kai's Nuclear Renaissance theme. Their uranium coverage has been the most prescient of any creator in the past 6 months.",
  },
  {
    id: "all-in",
    name: "All-In Podcast",
    handle: "@allin",
    specialty: "Tech, Macro, Venture Capital",
    videoCount: 38,
    avatar: "AI",
    avatarUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663185570724/QgiApnmXYRXSMA2KNkFFkL/all-in_421d15f4.jpg",
    color: "#101828",
    verified: true,
    bio: "The All-In Podcast features Chamath Palihapitiya, Jason Calacanis, David Sacks, and David Friedberg discussing tech, business, and macro trends. One of the most influential voices in Silicon Valley.",
    tags: ["Tech", "Macro", "Venture", "AI", "Policy"],
    youtubeUrl: "https://www.youtube.com/@allin",
    topTickers: ["MSFT", "GOOGL", "META", "AMZN", "NVDA"],
    kaiTake: "All-In's AI infrastructure thesis has been a consistent leading indicator for Kai's AI Supercycle theme. Their tariff analysis in E172 preceded the China Tariff Impact theme by 48 hours.",
  },
];

export const learningPaths = [
  {
    id: "beginner-foundations",
    title: "Market Foundations",
    level: "Beginner",
    lessonCount: 12,
    duration: "4h 30m",
    description: "Start here. Understand how markets work, what moves prices, and the vocabulary every trader needs.",
    topics: ["How Markets Work", "Reading Charts", "Order Types", "Risk Management Basics"],
    completionRate: 0,
    free: true,
  },
  {
    id: "technical-analysis-core",
    title: "Technical Analysis Core",
    level: "Intermediate",
    lessonCount: 18,
    duration: "7h 15m",
    description: "Master the chart patterns, indicators, and setups used by professional traders.",
    topics: ["Support & Resistance", "Moving Averages", "VCP Patterns", "Volume Analysis"],
    completionRate: 0,
    free: true,
  },
  {
    id: "options-fundamentals",
    title: "Options Fundamentals",
    level: "Intermediate",
    lessonCount: 15,
    duration: "6h 00m",
    description: "Understand options from first principles — Greeks, strategies, and how pros use them.",
    topics: ["Calls & Puts", "The Greeks", "Vertical Spreads", "Iron Condors"],
    completionRate: 0,
    free: false,
  },
  {
    id: "advanced-macro",
    title: "Advanced Macro Trading",
    level: "Advanced",
    lessonCount: 20,
    duration: "9h 45m",
    description: "Trade macro themes like an institutional investor. Yield curves, regime classification, cross-asset signals.",
    topics: ["Yield Curve Analysis", "Regime Classification", "Cross-Asset Signals", "Sector Rotation"],
    completionRate: 0,
    free: false,
  },
];

export const newsletterArchive = [
  {
    id: "nl-2025-04-07",
    date: "April 7, 2025",
    subject: "Nuclear Renaissance hits Level 4 — CCJ, NNE in focus",
    sentiment: "Bullish",
    topVideos: ["Macro Voices Nuclear Deep Dive", "Minervini VCP on CCJ", "Real Vision Energy Supercycle"],
    themeChanges: ["Nuclear Renaissance: Level 3 → 4", "Private Credit Stress: Escalating"],
    previewText: "The nuclear energy thesis is accelerating. Three new congressional trades in uranium names. Kai's convergence score on CCJ hit 93 this morning...",
  },
  {
    id: "nl-2025-04-06",
    date: "April 6, 2025",
    subject: "Tariff shock creates rotation opportunity — what the smart money is doing",
    sentiment: "Choppy",
    topVideos: ["All-In E172 Tariff Breakdown", "tastytrade Options Flow Alert", "SMB Capital Setups"],
    themeChanges: ["China Tariff Impact: New theme added", "Rate Cut Rotation: Watch → Active"],
    previewText: "Friday's tariff announcement created unusual options activity across tech. Dark pool prints suggest institutional buyers stepping in at key levels...",
  },
];

export const tickerData: Record<string, {
  ticker: string;
  score: number;
  direction: "Bullish" | "Bearish" | "Neutral";
  timeframe: string;
  confidence: string;
  price: string;
  change: string;
  changePercent: string;
  evidenceChain: { source: string; signal: string; detail: string; date: string }[];
  videosMentioning: typeof todaysPicks;
  relatedTickers: string[];
  theme: string;
  catalysts: string[];
  invalidationLevel: string;
}> = {
  NVDA: {
    ticker: "NVDA",
    score: 95,
    direction: "Bullish",
    timeframe: "Swing Trade",
    confidence: "Critical",
    price: "$875.40",
    change: "+21.10",
    changePercent: "+2.47%",
    evidenceChain: [
      { source: "Flow Agent", signal: "Unusual call buying", detail: "5,000 NVDA $900 calls purchased at open. Dark pool print of $2.1M at $870.", date: "Today" },
      { source: "News Agent", signal: "Positive catalyst", detail: "TSMC reported record AI chip orders. Blackwell demand exceeding supply estimates.", date: "Today" },
      { source: "Curated Content", signal: "Expert coverage", detail: "tastytrade covered unusual options activity. Minervini flagged VCP breakout setup on weekly chart.", date: "Yesterday" },
      { source: "Earnings Agent", signal: "Beat + raise", detail: "Last quarter: Revenue beat by 8%. Data center guidance raised 15%. Margins expanding.", date: "3 weeks ago" },
      { source: "Macro Agent", signal: "Regime tailwind", detail: "AI Infrastructure Supercycle theme at Level 5. Capex spending from hyperscalers accelerating.", date: "This week" },
    ],
    videosMentioning: [todaysPicks[2]],
    relatedTickers: ["AMD", "SMCI", "AVGO", "TSM"],
    theme: "AI Infrastructure Supercycle",
    catalysts: ["Blackwell ramp", "Hyperscaler capex", "Sovereign AI demand"],
    invalidationLevel: "Close below $840 on volume",
  },
  KKR: {
    ticker: "KKR",
    score: 88,
    direction: "Bearish",
    timeframe: "Swing Trade",
    confidence: "High",
    price: "$112.30",
    change: "-1.35",
    changePercent: "-1.19%",
    evidenceChain: [
      { source: "Insider Agent", signal: "Congressional trade", detail: "Senator on Banking Committee sold $250K KKR. Cross-referenced with committee hearing schedule.", date: "2 days ago" },
      { source: "Curated Content", signal: "Expert analysis", detail: "Real Vision covered private credit stress. Minervini noted supply zone at $92 based on demand theory.", date: "Today" },
      { source: "Flow Agent", signal: "Put buying", detail: "Elevated put/call ratio. $500K in $105 puts purchased. Institutional hedging activity.", date: "Today" },
      { source: "News Agent", signal: "Theme escalation", detail: "Private Credit Stress theme escalating for 3 weeks. 15 news signals in last 48 hours.", date: "This week" },
    ],
    videosMentioning: [todaysPicks[1]],
    relatedTickers: ["ARCC", "BX", "APO", "CG"],
    theme: "Private Credit Stress",
    catalysts: ["Credit spread widening", "Congressional scrutiny", "Rate environment"],
    invalidationLevel: "Close above $120 on volume",
  },
};
