"""AI persona agents that seed the community feed.

Cold-start solution. Posts are generated by Claude Haiku with a per-agent
voice prompt grounded in current market context (top movers from the
`tickers` table + latest `radar_snapshots` sentiment). Every post is
attributed to an `ai_agents` profile (is_agent=true, tier='agent') and
flows through the same `feed_posts` table as real posts, so the existing
social API surfaces it unchanged.

Safety:
    - Compliance guardrails baked into every system prompt
    - Never specific buy/sell prices
    - Posts disclaim AI persona status
    - `app_settings.agent_posting_enabled` is the hard off switch
    - Global daily spend cap shared with Kai via `kai_usage` table

Scheduling is wired in `main.py` — see `run_scheduled_post_job()`.
"""

from __future__ import annotations

import json
import logging
import random
import re
from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from typing import Any

import anthropic

from app.core.config import get_settings
from app.core.supabase import get_supabase
from app.services.kai_budget import estimate_cost_usd

log = logging.getLogger("ai_agent_poster")

# Model choice: Haiku 4.5 is cheap, fast, and plenty smart for short persona
# posts. If the voice starts feeling generic we can upgrade specific agents
# to Sonnet by adding a `model` column to ai_agents.
AGENT_MODEL = "claude-haiku-4-5-20251001"

# Hard daily circuit breaker for agent spend (separate from Kai's $200).
# Expected ~$0.05/day at 50 posts, so $5/day is a generous ceiling before
# something is catastrophically wrong.
AGENT_DAILY_SPEND_CAP_USD = 5.0

# Post-type distribution per agent style. Not all styles post the same
# kinds of things — Alex (day) mostly posts `market_take`, Samir (value)
# mostly `thesis`, Zoe (newbie) mostly `question`, Marcus (recap) posts
# `recap`. These feed into the prompt as the target post shape.
STYLE_POST_TYPES = {
    "day":        [("market_take", 0.75), ("question", 0.15), ("setup", 0.10)],
    "swing":      [("market_take", 0.45), ("setup", 0.35), ("thesis", 0.20)],
    "options":    [("market_take", 0.85), ("question", 0.15)],
    "macro":      [("market_take", 0.60), ("thesis", 0.40)],
    "crypto":     [("market_take", 0.80), ("question", 0.20)],
    "risk":       [("education", 1.00)],
    "value":      [("thesis", 0.70), ("education", 0.30)],
    "ta":         [("setup", 0.70), ("market_take", 0.30)],
    "contrarian": [("market_take", 0.50), ("thesis", 0.50)],
    "newbie":     [("question", 0.85), ("market_take", 0.15)],
    "meme":       [("market_take", 0.80), ("question", 0.20)],
    "news":       [("market_take", 1.00)],
    "recap":      [("recap", 1.00)],
    "earnings":   [("market_take", 0.60), ("thesis", 0.40)],
}

# Map our post-type vocabulary → values feed_posts.post_type already accepts.
# feed_posts has no CHECK constraint on post_type, but the frontend filters
# on it — so we keep the vocabulary small and stable.
POST_TYPE_NORMALIZATION = {
    "market_take": "take",
    "thesis":      "take",
    "setup":       "setup",
    "question":    "question",
    "education":   "take",
    "recap":       "take",
}


# ============================================================
# Data classes
# ============================================================

@dataclass
class AgentRow:
    """Flat representation of an agent row joined with its profile."""
    id: str                    # ai_agents.id
    profile_id: str            # profiles.id (used as feed_posts.user_id)
    persona_name: str
    handle: str
    display_name: str
    specialty: str
    style: str
    voice_prompt: str
    specialty_tickers: list[str]
    cadence_per_day: int
    market_hours_weight: float
    last_post_at: datetime | None
    post_count: int


@dataclass
class PostContent:
    body: str
    post_type: str
    sentiment: str | None           # bullish / bearish / neutral / None
    ticker: str | None              # primary ticker mentioned, if any
    tags: list[str]


# ============================================================
# Feature flag + spend guard
# ============================================================

def _load_setting(key: str, default: Any) -> Any:
    db = get_supabase()
    try:
        row = db.table("app_settings").select("value").eq("key", key).maybe_single().execute()
        if row is None or row.data is None:
            return default
        return row.data.get("value", default)
    except Exception as e:
        log.warning("app_settings read failed (%s): %s", key, e)
        return default


def is_agent_posting_enabled() -> bool:
    return bool(_load_setting("agent_posting_enabled", False))


def _global_agent_spend_today_usd() -> float:
    """Sum kai_usage.cost_usd for tier='agent' since start of UTC day."""
    db = get_supabase()
    day_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    try:
        rows = (
            db.table("kai_usage")
            .select("cost_usd")
            .eq("tier", "agent")
            .gte("created_at", day_start.isoformat())
            .execute()
        )
        return sum(float(r.get("cost_usd") or 0) for r in (rows.data or []))
    except Exception as e:
        log.warning("agent spend query failed: %s", e)
        return 0.0


def _record_agent_usage(profile_id: str, input_tokens: int, output_tokens: int) -> float:
    cost = estimate_cost_usd(AGENT_MODEL, input_tokens, output_tokens)
    db = get_supabase()
    try:
        db.table("kai_usage").insert({
            "user_id": profile_id,
            "conversation_id": None,
            "model": AGENT_MODEL,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "cost_usd": cost,
            "tier": "agent",
        }).execute()
    except Exception as e:
        log.error("failed to record agent usage: %s", e)
    return cost


# ============================================================
# Agent loading + selection
# ============================================================

def _get_active_agents() -> list[AgentRow]:
    db = get_supabase()
    rows = (
        db.table("ai_agents")
        .select("*, profiles!ai_agents_profile_id_fkey(id, handle, display_name)")
        .eq("active", True)
        .execute()
    )
    out: list[AgentRow] = []
    for r in (rows.data or []):
        prof = r.get("profiles") or {}
        last = r.get("last_post_at")
        last_dt = None
        if last:
            try:
                last_dt = datetime.fromisoformat(last.replace("Z", "+00:00"))
            except Exception:
                last_dt = None
        out.append(AgentRow(
            id=r["id"],
            profile_id=r["profile_id"],
            persona_name=r.get("persona_name") or "",
            handle=prof.get("handle") or "",
            display_name=prof.get("display_name") or "",
            specialty=r.get("specialty") or "",
            style=r.get("style") or "",
            voice_prompt=r.get("voice_prompt") or "",
            specialty_tickers=list(r.get("specialty_tickers") or []),
            cadence_per_day=int(r.get("cadence_per_day") or 3),
            market_hours_weight=float(r.get("market_hours_weight") or 0.75),
            last_post_at=last_dt,
            post_count=int(r.get("post_count") or 0),
        ))
    return out


def _is_market_hours_now() -> bool:
    """Rough US RTH check in UTC (9:30-16:00 ET → 13:30-20:00 UTC standard,
    12:30-19:00 UTC DST). Not exact — good enough for weighting."""
    now = datetime.now(timezone.utc)
    if now.weekday() >= 5:
        return False
    hour = now.hour + now.minute / 60
    return 13.0 <= hour <= 20.5


def _agent_weight(agent: AgentRow, now: datetime) -> float:
    """Weighted selection score. Higher = more likely to post next."""
    # Base weight from cadence (posts/day)
    weight = float(agent.cadence_per_day)

    # Cool down if posted recently (avoid back-to-back same agent)
    if agent.last_post_at is not None:
        minutes_since = (now - agent.last_post_at).total_seconds() / 60.0
        # Minimum spacing: ~ (1440 / cadence) minutes, with a 20-min floor
        min_spacing = max(20.0, 1440.0 / max(agent.cadence_per_day, 1))
        if minutes_since < min_spacing:
            weight *= 0.05
        elif minutes_since < min_spacing * 2:
            weight *= 0.5

    # Market hours bias
    if _is_market_hours_now():
        weight *= 1.0 + agent.market_hours_weight
    else:
        weight *= max(0.1, 1.0 - agent.market_hours_weight)
        # EOD recap agent biases HEAVILY toward post-close
        if agent.style == "recap" and 20.0 <= (now.hour + now.minute / 60) <= 22.0:
            weight *= 5.0

    return max(weight, 0.001)


def _pick_next_agent(agents: list[AgentRow]) -> AgentRow | None:
    if not agents:
        return None
    now = datetime.now(timezone.utc)
    weights = [_agent_weight(a, now) for a in agents]
    total = sum(weights)
    if total <= 0:
        return random.choice(agents)
    return random.choices(agents, weights=weights, k=1)[0]


# ============================================================
# Market context
# ============================================================

def _fetch_market_context(agent: AgentRow) -> dict:
    """Gather fresh, grounded context for the post prompt.

    - Top movers from `tickers` filtered by agent's specialty_tickers
      (or top overall convergence_score if the agent is macro/risk/newbie)
    - Latest radar_snapshots sentiment summary
    - Recent agent posts (last 2h) so we don't repeat ourselves
    """
    db = get_supabase()
    ctx: dict[str, Any] = {}

    # Specialty-filtered ticker snapshot
    try:
        q = db.table("tickers").select(
            "symbol, name, sector, last_price, price_change_pct, convergence_score, direction, catalyst"
        )
        if agent.specialty_tickers:
            q = q.in_("symbol", agent.specialty_tickers)
            res = q.order("price_change_pct", desc=True).limit(8).execute()
        else:
            res = q.order("convergence_score", desc=True).limit(10).execute()
        ctx["tickers"] = res.data or []
    except Exception as e:
        log.warning("ticker fetch failed: %s", e)
        ctx["tickers"] = []

    # Latest radar sentiment
    try:
        res = (
            db.table("radar_snapshots")
            .select("market_sentiment, sentiment_summary, created_at")
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        if res.data:
            ctx["radar"] = res.data[0]
    except Exception as e:
        log.warning("radar fetch failed: %s", e)

    # Recent feed posts (so we don't repeat)
    try:
        two_hours_ago = (datetime.now(timezone.utc) - timedelta(hours=2)).isoformat()
        res = (
            db.table("feed_posts")
            .select("body, ticker, created_at")
            .gte("created_at", two_hours_ago)
            .order("created_at", desc=True)
            .limit(10)
            .execute()
        )
        ctx["recent_posts"] = res.data or []
    except Exception as e:
        log.warning("recent posts fetch failed: %s", e)
        ctx["recent_posts"] = []

    return ctx


# ============================================================
# Prompt building
# ============================================================

COMPLIANCE_FOOTER = (
    "\n\nHARD RULES (never break):\n"
    "1. Never give specific entry, target, or stop prices.\n"
    "2. Never tell anyone to buy, sell, short, or close.\n"
    "3. Never cite a price as a forecast.\n"
    "4. Frame everything as observation, education, or scenario analysis.\n"
    "5. Stay in character. You are an AI persona — do not claim real trades or P&L.\n"
    "6. Output JSON matching the schema you are given. Nothing else.\n"
)


def _pick_post_type(style: str) -> str:
    options = STYLE_POST_TYPES.get(style, [("market_take", 1.0)])
    types = [t for t, _ in options]
    weights = [w for _, w in options]
    return random.choices(types, weights=weights, k=1)[0]


def _build_user_prompt(agent: AgentRow, context: dict, post_type: str) -> str:
    lines = [
        f"Write one social post as {agent.persona_name}.",
        f"Post type: {post_type}",
        "",
        "=== CURRENT MARKET CONTEXT (use only facts from here, do not invent) ===",
    ]

    radar = context.get("radar")
    if radar:
        lines.append(f"Market sentiment: {radar.get('market_sentiment','unknown')}")
        summ = radar.get("sentiment_summary") or ""
        if summ:
            lines.append(f"Sentiment summary: {summ[:300]}")

    tickers = context.get("tickers") or []
    if tickers:
        lines.append("")
        lines.append("Tickers on your radar right now (symbol, name, change%, convergence, direction, catalyst):")
        for t in tickers[:8]:
            chg = t.get("price_change_pct")
            chg_s = f"{chg:+.2f}%" if isinstance(chg, (int, float)) else "n/a"
            lines.append(
                f"- {t.get('symbol')} ({t.get('name') or '?'}) {chg_s} "
                f"conv={t.get('convergence_score',0)} dir={t.get('direction') or '?'} "
                f"catalyst={(t.get('catalyst') or '')[:80]}"
            )

    recent = context.get("recent_posts") or []
    if recent:
        lines.append("")
        lines.append("Recent posts in the feed (DO NOT REPEAT these angles or tickers already covered):")
        for p in recent[:6]:
            body = (p.get("body") or "")[:120].replace("\n", " ")
            lines.append(f"- [{p.get('ticker') or '-'}] {body}")

    lines.extend([
        "",
        "=== OUTPUT SCHEMA ===",
        "Return a JSON object and nothing else:",
        "{",
        '  "body": "<the post text — follow your voice rules strictly>",',
        '  "sentiment": "bullish" | "bearish" | "neutral" | null,',
        '  "ticker": "<primary ticker mentioned, or null>",',
        '  "tags": ["tag1","tag2"]',
        "}",
        "",
        "Tags should be 0-3 lowercase single-word topics (e.g. vwap, earnings, macro, flow, breakout).",
        "If the post is a question or education piece, sentiment should usually be null.",
        "Do NOT wrap the JSON in markdown code fences.",
    ])
    return "\n".join(lines)


# ============================================================
# Generation
# ============================================================

def _parse_post_json(text: str) -> dict | None:
    """Tolerant parser — strips code fences, finds first {...} block."""
    if not text:
        return None
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    # First JSON object
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1:
        return None
    try:
        return json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        return None


def generate_post_content(agent: AgentRow, dry_run: bool = False) -> PostContent | None:
    """Call Claude, return parsed PostContent. Records usage in kai_usage."""
    s = get_settings()
    if not s.anthropic_api_key:
        log.error("generate_post_content: no anthropic_api_key configured")
        return None

    context = _fetch_market_context(agent)
    post_type = _pick_post_type(agent.style)
    system = agent.voice_prompt + COMPLIANCE_FOOTER
    user = _build_user_prompt(agent, context, post_type)

    if dry_run:
        log.info("[dry_run] agent=%s post_type=%s", agent.handle, post_type)

    client = anthropic.Anthropic(api_key=s.anthropic_api_key)
    try:
        resp = client.messages.create(
            model=AGENT_MODEL,
            max_tokens=400,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
    except Exception as e:
        log.error("agent post generation failed (%s): %s", agent.handle, e)
        return None

    try:
        raw = resp.content[0].text if resp.content else ""
    except Exception:
        raw = ""

    # Record spend
    try:
        in_tok = getattr(resp.usage, "input_tokens", 0) or 0
        out_tok = getattr(resp.usage, "output_tokens", 0) or 0
        _record_agent_usage(agent.profile_id, in_tok, out_tok)
    except Exception as e:
        log.warning("usage recording failed for agent %s: %s", agent.handle, e)

    parsed = _parse_post_json(raw)
    if not parsed or not parsed.get("body"):
        log.warning("agent %s produced unparsable output: %r", agent.handle, raw[:200])
        return None

    body = str(parsed["body"]).strip()
    if len(body) < 10:
        log.warning("agent %s produced too-short body: %r", agent.handle, body)
        return None
    if len(body) > 600:
        body = body[:600].rsplit(" ", 1)[0] + "…"

    sentiment = parsed.get("sentiment")
    if sentiment not in ("bullish", "bearish", "neutral", None):
        sentiment = None

    ticker = parsed.get("ticker")
    if ticker:
        ticker = str(ticker).upper().strip()
        if not re.match(r"^[A-Z0-9.\-]{1,12}$", ticker):
            ticker = None

    tags = parsed.get("tags") or []
    if isinstance(tags, str):
        tags = [tags]
    tags = [str(t).lower().strip()[:20] for t in tags if t][:3]
    tags.append("ai_agent")  # makes filtering trivial

    return PostContent(
        body=body,
        post_type=POST_TYPE_NORMALIZATION.get(post_type, "take"),
        sentiment=sentiment,
        ticker=ticker,
        tags=tags,
    )


# ============================================================
# Posting
# ============================================================

def post_as_agent(agent: AgentRow, content: PostContent) -> str | None:
    """Insert into feed_posts, bump agent stats. Returns new post id."""
    db = get_supabase()
    row = {
        "user_id": agent.profile_id,
        "post_type": content.post_type,
        "body": content.body,
        "sentiment": content.sentiment,
        "ticker": content.ticker,
        "tags": content.tags,
    }
    try:
        res = db.table("feed_posts").insert(row).execute()
    except Exception as e:
        log.error("feed_posts insert failed for agent %s: %s", agent.handle, e)
        return None

    post_id = None
    if res.data:
        post_id = res.data[0].get("id")

    try:
        db.table("ai_agents").update({
            "last_post_at": datetime.now(timezone.utc).isoformat(),
            "post_count": agent.post_count + 1,
        }).eq("id", agent.id).execute()
    except Exception as e:
        log.warning("ai_agents stat update failed for %s: %s", agent.handle, e)

    log.info("agent post ok handle=%s post_id=%s ticker=%s", agent.handle, post_id, content.ticker)
    return post_id


# ============================================================
# Top-level scheduler entry points
# ============================================================

async def run_scheduled_post_job_async(max_posts: int = 1) -> dict:
    """Async shim for APScheduler (runs the sync implementation in a thread
    so blocking supabase / anthropic calls don't stall the event loop)."""
    import asyncio
    return await asyncio.to_thread(run_scheduled_post_job, max_posts)


def run_scheduled_post_job(max_posts: int = 1) -> dict:
    """Called by APScheduler every ~20 min during the day.

    Returns a small status dict for logs/telemetry.
    """
    status = {"enabled": False, "spend_ok": False, "agent": None, "post_id": None, "reason": None}

    if not is_agent_posting_enabled():
        status["reason"] = "disabled"
        return status
    status["enabled"] = True

    spend = _global_agent_spend_today_usd()
    if spend >= AGENT_DAILY_SPEND_CAP_USD:
        status["reason"] = f"daily cap hit (${spend:.2f}/${AGENT_DAILY_SPEND_CAP_USD})"
        log.warning("agent_poster: daily spend cap hit %.2f", spend)
        return status
    status["spend_ok"] = True

    agents = _get_active_agents()
    if not agents:
        status["reason"] = "no active agents"
        return status

    for _ in range(max_posts):
        agent = _pick_next_agent(agents)
        if not agent:
            break
        status["agent"] = agent.handle

        content = generate_post_content(agent)
        if not content:
            status["reason"] = "generation failed"
            continue

        post_id = post_as_agent(agent, content)
        if post_id:
            status["post_id"] = post_id
            # Remove this agent from candidates for subsequent iterations
            agents = [a for a in agents if a.id != agent.id]

    return status


# ============================================================
# Reply generation (threading)
# ============================================================

REPLY_COMPAT = {
    # bearish/contrarian responds to bullish swing/day/mega
    "contrarian": ["swing", "day", "meme", "newbie", "ta"],
    "risk":       ["day", "options", "swing", "meme"],
    "macro":      ["swing", "value", "contrarian"],
    "newbie":     ["day", "swing", "options", "macro", "ta", "value", "recap"],
    "ta":         ["swing", "day"],
    "value":      ["contrarian", "swing"],
}


def _pick_replier(agents: list[AgentRow], parent_author_style: str) -> AgentRow | None:
    pool = [a for a in agents if a.style != parent_author_style]
    if not pool:
        return None
    # Prefer explicitly compatible responders
    preferred = [
        a for a in pool
        if parent_author_style in REPLY_COMPAT.get(a.style, [])
    ]
    if preferred:
        return random.choice(preferred)
    return random.choice(pool)


def generate_reply_for_post(parent_post: dict) -> str | None:
    """30% chance, called after a new agent post is inserted."""
    if random.random() > 0.30:
        return None

    if not is_agent_posting_enabled():
        return None

    agents = _get_active_agents()
    if not agents:
        return None

    # Find the parent author's agent style
    parent_user = parent_post.get("user_id")
    author = next((a for a in agents if a.profile_id == parent_user), None)
    parent_style = author.style if author else "swing"

    replier = _pick_replier(agents, parent_style)
    if not replier:
        return None

    s = get_settings()
    if not s.anthropic_api_key:
        return None

    parent_body = (parent_post.get("body") or "")[:400]
    parent_ticker = parent_post.get("ticker") or ""
    system = replier.voice_prompt + COMPLIANCE_FOOTER
    user = (
        f"Another trader just posted this:\n"
        f"---\n{parent_body}\n---\n"
        f"Ticker: {parent_ticker or '-'}\n\n"
        f"Write a SHORT reply (1-2 sentences) in your voice. Do not agree reflexively — "
        f"if you disagree with the premise, say so directly but respectfully. "
        f"Output JSON: {{\"body\": \"...\"}} and nothing else."
    )

    client = anthropic.Anthropic(api_key=s.anthropic_api_key)
    try:
        resp = client.messages.create(
            model=AGENT_MODEL,
            max_tokens=200,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
    except Exception as e:
        log.warning("reply gen failed: %s", e)
        return None

    try:
        raw = resp.content[0].text if resp.content else ""
    except Exception:
        raw = ""

    try:
        in_tok = getattr(resp.usage, "input_tokens", 0) or 0
        out_tok = getattr(resp.usage, "output_tokens", 0) or 0
        _record_agent_usage(replier.profile_id, in_tok, out_tok)
    except Exception:
        pass

    parsed = _parse_post_json(raw)
    if not parsed or not parsed.get("body"):
        return None

    body = str(parsed["body"]).strip()
    if len(body) < 5:
        return None
    if len(body) > 400:
        body = body[:400].rsplit(" ", 1)[0] + "…"

    # Insert as comment
    db = get_supabase()
    try:
        db.table("post_comments").insert({
            "post_id": parent_post.get("id"),
            "user_id": replier.profile_id,
            "body": body,
        }).execute()
        # Bump comments_count on parent
        current_count = int(parent_post.get("comments_count") or 0)
        db.table("feed_posts").update({
            "comments_count": current_count + 1,
        }).eq("id", parent_post.get("id")).execute()
        db.table("ai_agents").update({
            "last_reply_at": datetime.now(timezone.utc).isoformat(),
        }).eq("id", replier.id).execute()
    except Exception as e:
        log.warning("reply insert failed: %s", e)
        return None

    log.info("agent reply ok replier=%s parent=%s", replier.handle, parent_post.get("id"))
    return body


# ============================================================
# Dry-run helper (used by the verify-samples script)
# ============================================================

def dry_run_samples(n: int = 5) -> list[dict]:
    """Generate N sample posts without inserting anything. For manual review."""
    agents = _get_active_agents()
    if not agents:
        return []
    samples = []
    for _ in range(n):
        agent = _pick_next_agent(agents) or random.choice(agents)
        content = generate_post_content(agent, dry_run=True)
        if not content:
            samples.append({"agent": agent.handle, "error": "generation failed"})
            continue
        samples.append({
            "agent": agent.handle,
            "persona": agent.persona_name,
            "style": agent.style,
            "post_type": content.post_type,
            "body": content.body,
            "sentiment": content.sentiment,
            "ticker": content.ticker,
            "tags": content.tags,
        })
    return samples
